--CREATE DATABASE ESTOQUE2;

USE ESTOQUE2

GO

SELECT * FROM PRODUTO;


/*CREATE TABLE PRODUTO(
    Id INT identity(1,1) NOT NULL,
    Nome VARCHAR(50) NOT NULL,

    Marca VARCHAR(30) NOT NULL,

    DataVencimento DATE NOT NULL,

    PrecoUnitario DECIMAL(11,2) NOT NULL,

    Unidade VARCHAR(20) NOT NULL,

    QtEstoque INT NOT NULL
)*/