using System;

namespace exer03
{
    class Program
    {
        static void Main(string[] args)
        {
            //pt1
            Console.WriteLine("Digite 1 caractere:");
            var X = Console.ReadLine();
            Console.WriteLine(" ");
             Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(X);
            Console.WriteLine("");

            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.WriteLine("");

            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.WriteLine("");

            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.WriteLine("");

            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.WriteLine("");

            Console.Write(" ");
            Console.Write(" ");
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.WriteLine("");

            Console.Write(" ");
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.WriteLine("");

            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.WriteLine(" ");
            Console.WriteLine(" ");

            //pt2
            Console.WriteLine("Digite 1 caractere:");
            X = Console.ReadLine();
            Console.WriteLine(" ");
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.WriteLine(" ");
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.WriteLine(" ");
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.WriteLine(" ");
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.WriteLine(" ");
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.WriteLine(" ");
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.Write(X);
            Console.WriteLine(" ");
            Console.WriteLine(" ");

            //pt3
            Console.WriteLine("Digite 1 caractere:");
            X = Console.ReadLine();
            Console.WriteLine(" ");
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("  ");
            Console.BackgroundColor = ConsoleColor.DarkBlue;
            Console.Write(X+X+X+X+X+X+X+X);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("    ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write(X+X);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("      ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write(X+X);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.WriteLine("");
            Console.BackgroundColor = ConsoleColor.DarkBlue;
            Console.Write(X+X);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("        ");
            Console.Write("  ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write(X+X+X+X+X+X+X+X+X+X+X+X+X+X);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.WriteLine("");
            Console.BackgroundColor = ConsoleColor.DarkBlue;
            Console.Write(X+X);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("        ");
            Console.Write("    ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write(X+X);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("      ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write(X+X);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.WriteLine("");
            Console.BackgroundColor = ConsoleColor.DarkBlue;
            Console.Write(X+X);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("        ");
            Console.Write("    ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write(X+X);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("      ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write(X+X);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.WriteLine("");
            Console.BackgroundColor = ConsoleColor.DarkBlue;
            Console.Write(X+X);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("        ");
            Console.Write("  ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write(X+X+X+X+X+X+X+X+X+X+X+X+X+X);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.WriteLine("");
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("  ");
            Console.BackgroundColor = ConsoleColor.DarkBlue;
            Console.Write(X+X+X+X+X+X+X+X);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("    ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write(X+X);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("      ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write(X+X);
            Console.BackgroundColor = ConsoleColor.Black;
            Console.WriteLine(" ");
            Console.WriteLine(" ");

        }
    }
}
