using System;

namespace exer01 
{
    class Program
    {
        static void Main (string[] args)
        {
    //pt1
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write("#");
            Console.WriteLine("");

            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.WriteLine("");

            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.WriteLine("");

            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.WriteLine("");

            Console.Write(" ");
            Console.Write(" ");
            Console.Write(" ");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.WriteLine("");

            Console.Write(" ");
            Console.Write(" ");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.WriteLine("");

            Console.Write(" ");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.WriteLine("");

            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.WriteLine(" ");
            Console.WriteLine(" ");

    //pt2
            Console.Write(" ");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.WriteLine("");
            Console.Write(" ");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.WriteLine("");
            Console.Write(" ");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.WriteLine("");
            Console.Write(" ");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.WriteLine("");
            Console.Write(" ");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.WriteLine("");
            Console.Write(" ");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.Write("#");
            Console.WriteLine(" ");
            Console.WriteLine(" ");

    //pt3
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("  ");
            Console.BackgroundColor = ConsoleColor.DarkBlue;
            Console.Write("########");
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("    ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write("##");
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("      ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write("##");
            Console.BackgroundColor = ConsoleColor.Black;
            Console.WriteLine("");
            Console.BackgroundColor = ConsoleColor.DarkBlue;
            Console.Write("##");
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("        ");
            Console.Write("  ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write("##############");
            Console.BackgroundColor = ConsoleColor.Black;
            Console.WriteLine("");
            Console.BackgroundColor = ConsoleColor.DarkBlue;
            Console.Write("##");
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("        ");
            Console.Write("    ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write("##");
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("      ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write("##");
            Console.BackgroundColor = ConsoleColor.Black;
            Console.WriteLine("");
            Console.BackgroundColor = ConsoleColor.DarkBlue;
            Console.Write("##");
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("        ");
            Console.Write("    ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write("##");
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("      ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write("##");
            Console.BackgroundColor = ConsoleColor.Black;
            Console.WriteLine("");
            Console.BackgroundColor = ConsoleColor.DarkBlue;
            Console.Write("##");
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("        ");
            Console.Write("  ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write("##############");
            Console.BackgroundColor = ConsoleColor.Black;
            Console.WriteLine("");
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("  ");
            Console.BackgroundColor = ConsoleColor.DarkBlue;
            Console.Write("########");
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("    ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write("##");
            Console.BackgroundColor = ConsoleColor.Black;
            Console.Write("      ");
            Console.BackgroundColor = ConsoleColor.Red;
            Console.Write("##");
            Console.BackgroundColor = ConsoleColor.Black;
            Console.WriteLine(" ");
            Console.WriteLine(" ");
            

    //pt4
            Console.WriteLine("Informe seu nome: ");
            var nome = Console.ReadLine();
            Console.Write("Olá ");
            Console.ForegroundColor = ConsoleColor.DarkBlue;
            Console.WriteLine(nome);
            Console.ForegroundColor = ConsoleColor.White;
            Console.WriteLine("Informe sua idade: ");
            var idade = Console.ReadLine();
            Console.Write("Parabéns, você tem ");
            Console.ForegroundColor = ConsoleColor.Yellow;
            Console.Write(idade);
            Console.ForegroundColor = ConsoleColor.White;
            Console.WriteLine(" anos!");
        }
    }
}